### ISSUE TITLE
nil-pointer executing 'pki.io org run'

### ISSUE THREAD

**Issue by brasilikum** [pki-io/docs#8]
I was following the `Getting started` on the website. I ran all the steps until I hit a nil pointer while executing `pki.io org run`. 
I am using version `pki.io_0.1.2-release1_darwin_amd64.tar.gz`
I am currently running  OSX 10.11 Beta (15A278b)

The full output was:

```
Loading admin app
Loading admin config
Loading admin entity
Loading org entity
Registering nodes
Found 1 nodes to register
Reading pairing key: 70ddaa68f47de74fe04f308ada6c8db1
Verifying and decrypting node registration
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x993e]

goroutine 1 [running]:
main.(*AdminApp).RegisterNextNode(0xc208030580)
    /var/folders/n1/4ss_2rt10396zylvvdsjqv5cm4l758/T/tmp.2Bw6hUlTsM/go/src/github.com/pki-io/admin/adminApp.go:366 +0x13ce
main.(*AdminApp).RegisterNodes(0xc208030580)
    /var/folders/n1/4ss_2rt10396zylvvdsjqv5cm4l758/T/tmp.2Bw6hUlTsM/go/src/github.com/pki-io/admin/adminApp.go:412 +0x2f3
main.orgRun(0xc20806e690, 0x0, 0x0)
    /var/folders/n1/4ss_2rt10396zylvvdsjqv5cm4l758/T/tmp.2Bw6hUlTsM/go/src/github.com/pki-io/admin/runOrg.go:22 +0x6b
main.runOrg(0xc20806a9a0, 0x2, 0x2, 0x0, 0x0)
    /var/folders/n1/4ss_2rt10396zylvvdsjqv5cm4l758/T/tmp.2Bw6hUlTsM/go/src/github.com/pki-io/admin/runOrg.go:42 +0x21b
main.runCommand(0x7fff5fbffb37, 0x3, 0xc20802b880, 0x1, 0x1, 0x0, 0x0)
    /var/folders/n1/4ss_2rt10396zylvvdsjqv5cm4l758/T/tmp.2Bw6hUlTsM/go/src/github.com/pki-io/admin/pki.io.go:75 +0x69c
main.main()
    /var/folders/n1/4ss_2rt10396zylvvdsjqv5cm4l758/T/tmp.2Bw6hUlTsM/go/src/github.com/pki-io/admin/pki.io.go:52 +0x4b7

goroutine 5 [semacquire]:
sync.(*Cond).Wait(0xc208030800)
    /usr/local/go/src/sync/cond.go:62 +0x9e
github.com/cihub/seelog.(*asyncLoopLogger).processItem(0xc208050360, 0x42600)
    /var/folders/n1/4ss_2rt10396zylvvdsjqv5cm4l758/T/tmp.2Bw6hUlTsM/go/src/github.com/pki-io/admin/_vendor/src/github.com/cihub/seelog/behavior_asynclooplogger.go:50 +0xc2
github.com/cihub/seelog.(*asyncLoopLogger).processQueue(0xc208050360)
    /var/folders/n1/4ss_2rt10396zylvvdsjqv5cm4l758/T/tmp.2Bw6hUlTsM/go/src/github.com/pki-io/admin/_vendor/src/github.com/cihub/seelog/behavior_asynclooplogger.go:63 +0x31
created by github.com/cihub/seelog.newAsyncLoopLogger
    /var/folders/n1/4ss_2rt10396zylvvdsjqv5cm4l758/T/tmp.2Bw6hUlTsM/go/src/github.com/pki-io/admin/_vendor/src/github.com/cihub/seelog/behavior_asynclooplogger.go:40 +0x8e

goroutine 6 [semacquire]:
sync.(*Cond).Wait(0xc2080309c0)
    /usr/local/go/src/sync/cond.go:62 +0x9e
github.com/cihub/seelog.(*asyncLoopLogger).processItem(0xc208050480, 0x0)
    /var/folders/n1/4ss_2rt10396zylvvdsjqv5cm4l758/T/tmp.2Bw6hUlTsM/go/src/github.com/pki-io/admin/_vendor/src/github.com/cihub/seelog/behavior_asynclooplogger.go:50 +0xc2
github.com/cihub/seelog.(*asyncLoopLogger).processQueue(0xc208050480)
    /var/folders/n1/4ss_2rt10396zylvvdsjqv5cm4l758/T/tmp.2Bw6hUlTsM/go/src/github.com/pki-io/admin/_vendor/src/github.com/cihub/seelog/behavior_asynclooplogger.go:63 +0x31
created by github.com/cihub/seelog.newAsyncLoopLogger
    /var/folders/n1/4ss_2rt10396zylvvdsjqv5cm4l758/T/tmp.2Bw6hUlTsM/go/src/github.com/pki-io/admin/_vendor/src/github.com/cihub/seelog/behavior_asynclooplogger.go:40 +0x8e

goroutine 7 [runnable]:
sync.(*Cond).Wait(0xc208031600)
    /usr/local/go/src/sync/cond.go:62 +0x9e
github.com/cihub/seelog.(*asyncLoopLogger).processItem(0xc2080509c0, 0x0)
    /var/folders/n1/4ss_2rt10396zylvvdsjqv5cm4l758/T/tmp.2Bw6hUlTsM/go/src/github.com/pki-io/admin/_vendor/src/github.com/cihub/seelog/behavior_asynclooplogger.go:50 +0xc2
github.com/cihub/seelog.(*asyncLoopLogger).processQueue(0xc2080509c0)
    /var/folders/n1/4ss_2rt10396zylvvdsjqv5cm4l758/T/tmp.2Bw6hUlTsM/go/src/github.com/pki-io/admin/_vendor/src/github.com/cihub/seelog/behavior_asynclooplogger.go:63 +0x31
created by github.com/cihub/seelog.newAsyncLoopLogger
    /var/folders/n1/4ss_2rt10396zylvvdsjqv5cm4l758/T/tmp.2Bw6hUlTsM/go/src/github.com/pki-io/admin/_vendor/src/github.com/cihub/seelog/behavior_asynclooplogger.go:40 +0x8e
```

**Comment by thanasisk** [comment]
Thank you for bringing this to our attention. @zeroXten if I am not mistaken you have access to OSX machines right?

**Comment by zeroXten** [comment]
Yeah, I just tried to replicate it. I downloaded v0.1.2 and followed the getting started instructions. Interesting, "org run" worked fine, but I actually get a panic on "node cert"... which sucks.

I'll dig into the latter, but @Brasilikum could you please provide the full command you ran and the output? Assuming you can share the pairing keys etc. I suspect that it can't find the pairing key by the id.

**Comment by brasilikum** [comment]
Hi @zeroXten,
I ran all the steps in "Getting started" until the mentioned `pki.io org run`
The command with the pairing-key and pairing-id was:

```
pki.io node new web01 --pairing-id 70ddaa68f47de74fe04f308ada6c8db1 \
    --pairing-key 4eb44b2911fcbb7a40ba2d012c0bfaaf
```

Hope that helps you in debugging

**Comment by zeroXten** [comment]
Cheers @Brasilikum. I can't reproduce your problem at the moment. Could you take a look at my commands and see if you've done anything different?

Firstly I'll set PKIIO_HOME to stop it touching my existing stuff.

```
$ export PKIIO_HOME=$PWD
```

Matching version

```
$ pki.io --version
pki.io 0.1.2-release1
```

Following the interesting bits of the Getting Started guide.

```
$ pki.io init my-org
Creating Admin entity
Generating admin keys
Creating Org entity
Generating Org keys
Saving local admin
Saving public admin
Creating org index
Saving org public entity to home
Saving admin config

$ cd my-org

$ pki.io ca new web-root --tags web \
>     --dn-o pki.io --dn-ou webops
Loading admin app
Loading admin config
Loading admin entity
Loading org entity
Saving CA
Updating index

$  pki.io cert new test-web-1 --expiry 60 --ca web-root \
>     --dn-o pki.io --dn-ou web-test --export test1.tar.gz
Loading admin app
Loading admin config
Loading admin entity
Loading org entity
Export to 'test1.tar.gz'

$ tar -zxOf test1.tar.gz test-web-1-cert.pem | \
>     openssl x509 -noout -subject -issuer -startdate -enddate
subject= /O=pki.io/OU=web-test/CN=test-web-1
issuer= /O=pki.io/OU=webops/CN=web-root
notBefore=Sep  6 20:55:58 2015 GMT
notAfter=Nov  5 21:55:58 2015 GMT

$ pki.io pairing-key new --tags web
Loading admin app
Loading admin config
Loading admin entity
Loading org entity
Creating the key
Saving key to index
Pairing ID: d341c20ff5c03a36a381e074c0823856
Pairing key: 085a0e3a5de8b77a6a8bfa989c59cec3


$ pki.io node new web01 --pairing-id d341c20ff5c03a36a381e074c0823856 --pairing-key 085a0e3a5de8b77a6a8bfa989c59cec3
Loading admin app
Loading admin config
Loading admin entity
Loading org entity
Creating new node
Generating node keys
Encrypting node for org
Pushing container to org
Switching to node context
Creating node index
Creating node config
Creating CSRs
Generating CSRs
...
Saving node index

$ pki.io org run
Loading admin app
Loading admin config
Loading admin entity
Loading org entity
Registering nodes
Found 1 nodes to register
Reading pairing key: d341c20ff5c03a36a381e074c0823856
Verifying and decrypting node registration
Adding node to index
Encrypting and signing node for Org
Looking for CAs for tag web
Found CA 114213176031935795330325995604071157846
Getting CSR for node
Setting CSR name from node
Getting CA
Creating certificate
Tagging cert
Signing cert
Pushing certificate to node
Found 0 nodes to register


$ pki.io node run --name web01
Loading admin app
Loading admin config
Loading admin entity
Loading org entity
Loading node app
Loading node index
Processing certs
Found 1 certs to process
Found 0 certs to process
Saving node index

$ pki.io node cert --name web01 --tags web --export - | \
>     tar -zxOf - web01-cert.pem | openssl x509 -noout -subject -issuer -startdate -enddate
panic: interface conversion: interface is nil, not string
```

So it fails for me when doing "node cert".

**Comment by brasilikum** [comment]
`pki.io org run` works now, I think I mixed something up with the names the first time.
I can reproduce your panic. It fails with the exact same message at `pki.io node cert` as well.

**Comment by zeroXten** [comment]
Ah cool :)

That is still a bug of course, the nil pointer panic suggests we're not checking something properly. That sort of thing should be mostly sorted after the refactoring.. having said that, I'll still dig into it to make sure that the it is better in the next release.

I've created a placeholder ticket #9 for the cert issue. Will fill out the details and hopefully resolve this evening or in the next few days.

**Comment by zeroXten** [comment]
@Brasilikum - currently building 0.1.3 so hopefully that will be released tonight and includes the "node cert" fix. I have a theory about why you got a "org run" panic.

When running "node new", if you get the pairing id or pairing key wrong, the "node new" command has no way of telling. It will happily encrypt and HMAC its registration data using the provided keys. When it then comes to running "org run", the org sees the registration but either it can't find the id that was used, or it can't decrypt it.

I'll add some guards in to ensure it returns sensible errors at the right place if the id can't be found or decrypted, and I have also created a ticket to add a checksum mechanism into the pairing. I'm thinking something like a truncated SHA1 of id + key, appended to the key. That way a copy/paste error of either the id or key, or an id/key mismatch would (probably) result in a checksum failure and "node new" could fail with a sensible error.

**Comment by brasilikum** [comment]
@zeroXten, sounds great. I am totally in favour of a checksum, the earlier the user gets a feedback about possible problems, the less frustrated he will be. It sounds reasonable to assume that I made some kind of coping mistake, as I was adapting the example with custom names and of course ids and keys.

**Comment by brasilikum** [comment]
I tried to run 0.1.3 myself, was password protected :)

**Comment by zeroXten** [comment]
Password protected?

**Comment by brasilikum** [comment]
Well, tar askted me for a password. But I might have mixed up the parameters. Was trying to repeat the `getting started` with the new build. Nevermind, I will try again

**Comment by zeroXten** [comment]
Ah ok. Yeah, give it another go. The tars aren't encrypted.
